// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...f
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91M7PcpnZf29k4RdU8TOy01bQcGiBfeg',
    appId: '1:280935595423:web:88d01af02c273e9c04d1aa',
    messagingSenderId: '280935595423',
    projectId: 'localink-7438c',
    authDomain: 'localink-7438c.firebaseapp.com',
    storageBucket: 'localink-7438c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-DpedAV-Pgdf-cATEA-clq8CiuTY3s4',
    appId: '1:280935595423:android:5078795c3c2177aa04d1aa',
    messagingSenderId: '280935595423',
    projectId: 'localink-7438c',
    storageBucket: 'localink-7438c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdAy-HRTe1bvAOsi5UiMwtpWI6czcW5M',
    appId: '1:280935595423:ios:ef7227fc6459c87104d1aa',
    messagingSenderId: '280935595423',
    projectId: 'localink-7438c',
    storageBucket: 'localink-7438c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdAy-HRTe1bvAOsi5UiMwtpWI6czcW5M',
    appId: '1:280935595423:ios:ef7227fc6459c87104d1aa',
    messagingSenderId: '280935595423',
    projectId: 'localink-7438c',
    storageBucket: 'localink-7438c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91M7PcpnZf29k4RdU8TOy01bQcGiBfeg',
    appId: '1:280935595423:web:d353d8c77ef4420d04d1aa',
    messagingSenderId: '280935595423',
    projectId: 'localink-7438c',
    authDomain: 'localink-7438c.firebaseapp.com',
    storageBucket: 'localink-7438c.firebasestorage.app',
  );
}
